### PR TITLE
Error when other classes that extend Time call `now`

### PR DESCRIPTION
**Pull request by lmc**
Ran into a problem where an OpenOffice parsing gem was failing with "no implicit conversion to float from nil". Tracked it down to a DOSTime class that extends Time that was failing due to interactions with time-warp.
Included is a small tweak to stop that happening, with a test.

### CODE REVIEW

**Comment by KevinTriplett** [comment]
+1

Thanks, this fixes my issue with cucumber-selenium tests failing with cryptic "can't convert nil into an exact number (TypeError)" when calling `#visit` method for browser.

Another solution is `cattr_accessor` but that means the subclasses have access to `timing_offset`, which might not be desirable (but they shouldn't know or care about it).

**Comment by bjhess** [comment]
Interestingly we are seeing a conflict with rubyzip today as we upgrade Harvest to Ruby 1.9.3, and this fix gets things partially resolved. There is more to it, I fear, so I will be working on further tweaks before releasing an update.

Thanks for the pull request!

**Comment by bjhess** [comment]
Added one more fix and released version 1.0.12: http://rubygems.org/gems/time-warp

**Comment by KevinTriplett** [comment]
Fixes my issues -- thanks :D

**Pull request merged**
