### PR TITLE
Add MiniTest support

### PR DESCRIPTION
**Pull request by tjschuck**
@bjhess I got you this MiniTest support.

### CODE REVIEW

**Comment by tjschuck** [comment]
Might have spoken too soon.  Feel free to sit on this for a while until I confirm if the problem is with Time Warp or something else...

**Comment by bjhess** [comment]
Sitting.

**Comment by tjschuck** [comment]
Sit no longer.  Did some more testing -- this appears to be sufficient.

**Comment by bjhess** [comment]
I will have to trust you. With a +1.

**Comment by bjhess** [comment]
+1

**Pull request merged**
